name: FinTrackAI CI/CD

on:
  push:
    branches: ["main", "frontend"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run CI/CD Shell Script
        run: |
          chmod +x frontend/cicd.sh
          frontend/cicd.sh
